import { 
  LayoutDashboard, Sun, CheckSquare, Calendar, Target,
  Wallet, Lightbulb, FolderOpen, PieChart,
  BookOpen, Book, RotateCw, PlaySquare, FileText, Users, Receipt
} from "lucide-react";

export type ModuleCategory = "System" | "Productivity" | "Money" | "Personal";

export interface SystemModule {
  id: string;
  label: string;
  icon: any;
  route: string;
  category: ModuleCategory;
  description: string;
  defaultEnabled: boolean;
  supportsQuickAdd: boolean;
  supportsDashboardWidget: boolean;
  implemented: boolean;
}

export const SYSTEM_MODULES: Record<string, SystemModule> = {
  dashboard: {
    id: "dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    route: "/dashboard",
    category: "System",
    description: "Your personal overview and widgets",
    defaultEnabled: true,
    supportsQuickAdd: false,
    supportsDashboardWidget: false,
    implemented: true,
  },
  today: {
    id: "today",
    label: "Today",
    icon: Sun,
    route: "/dashboard/today",
    category: "System",
    description: "Your daily focus and summary",
    defaultEnabled: true,
    supportsQuickAdd: false,
    supportsDashboardWidget: true,
    implemented: true,
  },
  tasks: {
    id: "tasks",
    label: "Tasks",
    icon: CheckSquare,
    route: "/dashboard/tasks",
    category: "Productivity",
    description: "Manage your daily work and to-dos",
    defaultEnabled: true,
    supportsQuickAdd: true,
    supportsDashboardWidget: true,
    implemented: true,
  },
  projects: {
    id: "projects",
    label: "Projects",
    icon: FolderOpen,
    route: "/dashboard/projects",
    category: "Productivity",
    description: "Organize larger initiatives",
    defaultEnabled: true,
    supportsQuickAdd: true,
    supportsDashboardWidget: true,
    implemented: false,
  },
  calendar: {
    id: "calendar",
    label: "Calendar",
    icon: Calendar,
    route: "/dashboard/calendar",
    category: "Productivity",
    description: "Your schedule and events",
    defaultEnabled: true,
    supportsQuickAdd: true,
    supportsDashboardWidget: true,
    implemented: false,
  },
  routines: {
    id: "routines",
    label: "Routines",
    icon: RotateCw,
    route: "/dashboard/routines",
    category: "Productivity",
    description: "Daily and weekly recurring flows",
    defaultEnabled: true,
    supportsQuickAdd: false,
    supportsDashboardWidget: true,
    implemented: true,
  },
  habits: {
    id: "habits",
    label: "Habits",
    icon: PlaySquare,
    route: "/dashboard/habits",
    category: "Productivity",
    description: "Track your personal habits",
    defaultEnabled: true,
    supportsQuickAdd: false,
    supportsDashboardWidget: true,
    implemented: false,
  },
  goals: {
    id: "goals",
    label: "Goals",
    icon: Target,
    route: "/dashboard/goals",
    category: "Productivity",
    description: "Long-term targets and milestones",
    defaultEnabled: true,
    supportsQuickAdd: true,
    supportsDashboardWidget: true,
    implemented: false,
  },
  ideas: {
    id: "ideas",
    label: "Ideas",
    icon: Lightbulb,
    route: "/dashboard/ideas",
    category: "Productivity",
    description: "Inbox for thoughts and inspiration",
    defaultEnabled: true,
    supportsQuickAdd: true,
    supportsDashboardWidget: true,
    implemented: true,
  },
  notes: {
    id: "notes",
    label: "Notes",
    icon: BookOpen,
    route: "/dashboard/notes",
    category: "Productivity",
    description: "Fast, personal text notes",
    defaultEnabled: true,
    supportsQuickAdd: true,
    supportsDashboardWidget: false,
    implemented: false,
  },
  journal: {
    id: "journal",
    label: "Journal",
    icon: Book,
    route: "/dashboard/journal",
    category: "Productivity",
    description: "Private daily logging",
    defaultEnabled: true,
    supportsQuickAdd: true,
    supportsDashboardWidget: false,
    implemented: false,
  },
  money: {
    id: "money",
    label: "Money",
    icon: Wallet,
    route: "/dashboard/money",
    category: "Money",
    description: "Track balances, income, and expenses",
    defaultEnabled: true,
    supportsQuickAdd: true,
    supportsDashboardWidget: true,
    implemented: true,
  },
  investments: {
    id: "investments",
    label: "Investments",
    icon: PieChart,
    route: "/dashboard/investments",
    category: "Money",
    description: "Track your portfolio and holdings",
    defaultEnabled: false,
    supportsQuickAdd: true,
    supportsDashboardWidget: true,
    implemented: false,
  },
  reports: {
    id: "reports",
    label: "Reports",
    icon: Receipt,
    route: "/dashboard/reports",
    category: "Money",
    description: "Financial summaries and analytics",
    defaultEnabled: true,
    supportsQuickAdd: false,
    supportsDashboardWidget: false,
    implemented: false,
  },
  documents: {
    id: "documents",
    label: "Documents",
    icon: FileText,
    route: "/dashboard/documents",
    category: "Personal",
    description: "Important files and records",
    defaultEnabled: false,
    supportsQuickAdd: true,
    supportsDashboardWidget: false,
    implemented: false,
  },
  contacts: {
    id: "contacts",
    label: "Contacts",
    icon: Users,
    route: "/dashboard/contacts",
    category: "Personal",
    description: "People network",
    defaultEnabled: false,
    supportsQuickAdd: true,
    supportsDashboardWidget: false,
    implemented: false,
  }
};
